### ISSUE TITLE
A non-numeric value encountered - error on line 272

### ISSUE THREAD

**Issue by AndreiGhitan** [AaronVanGeffen/AwstatsParser#3] opened 2017-11-27 12:59 UTC
I just tried using your tool, great tool btw.

One bug I came across is that after I merged 2 log files, in awstats it displays the following error message:

Error: History file '/home/usr/tmp/awstats/awstats012017.mydomain.com.txt' is to old (version '0'). This version of AWStats is not compatible with very old history files. Remove this history file or use first a previous AWStats version to migrate it from command line with command: awstats.pl -migrate="/home/usr/tmp/awstats/awstats012017.proxyape.com.txt".

And in the file the first 2 lines ar giving me this output:

Warning: A non-numeric value encountered in /Users/myuser/Downloads/Awmerge/src/AaronVanGeffen/AwstatsParser/AwstatsMerger.php on line 272

Warning: A non-numeric value encountered in /Users/myuser/Downloads/Awmerge/src/AaronVanGeffen/AwstatsParser/AwstatsMerger.php on line 272
AWSTATS DATA FILE 6.9 (build 1.925)

Is there any way you could update it?

Thank you for building this tool!

**Comment by AaronVanGeffen** [comment] 2017-12-01 21:30
First off, thank you for using my script, and for filing a bug report!

The first line of the output file is read by Awstats to detect the version used to produce the data file. The script writes version 6.9 by default, while version 7.6 is the newest.

In your case, it seems the version cannot be detected because the first line contains a PHP error message. Removing the errors from the output file, such that the first line contains the Awstats version, should make the file readable by Awstats again.

Now, the question is why this problem arises in the first place. I am unable to reproduce it myself with data files generated by version 7.6. It is certainly conceivable, though, that two lines in one of your files are read incorrectly. I will need your help debugging that, though.

Could you replace the following lines in AwstatsMerge.php (271-273):
```php
            foreach ($row as $num => $stats)
                $this->data[$section_name][$key][$num] += $stats;
        }
```

with these:
```php
            foreach ($row as $num => $stats)
            {
                if (is_numeric($stats))
                    $this->data[$section_name][$key][$num] += $stats;
                else
                {
                    echo 'Section name: ', $section_name, "\n",
                        'Key: ', $key, "\n",
                        'Num: ', $num, "\n",
                        'Stats: ', $stats, "\n";
                }
            }
        }
        exit;    
```

This change should make the script terminate after outputting details on the offending lines. Note: the exit statement should be the last statement in the function. 

Please find the offending lines in the files you're trying to merge, and report them here.

**Comment by AndreiGhitan** [comment] 2017-12-04 11:52
I have changed the lines as instructed by you, I will do a test later today and report if it solved the issue, in case it didn't, I will post the files.

Thank you for building this script, it works like a charm and everything is pretty straight forward.

Keep up the good work Aaron!

**Comment by AaronVanGeffen** [comment] 2017-12-30 13:19
I'm assuming the issue was resolved. Closing this.

**Closed by AaronVanGeffen** 2017-12-30 13:19 UTC
Labels: bug
